### ISSUE TITLE
How to adjust the grid lines of the graph, the length of the X-axis, etc？

### ISSUE THREAD

**Issue by 13367356107** [lozalojo/memapp#3]
Hello author, I would like to ask you how to adjust the specific parameters of the series chart made by mem dashboard? For example I want to hide gridlines, or adjust the length of the X axis.

**Comment by lozanoje** [comment]
> Hello author, I would like to ask you how to adjust the specific parameters of the series chart made by mem dashboard? For example I want to hide gridlines, or adjust the length of the X axis.

You cant, though graphs looks interactive, in fact they arent; graphs are pregenerated, I added some parameters to configure axis titles that are parsed before generating the graph, but there are no options for gridlines or x-axis length.

**Comment by 13367356107** [comment]
Can I achieve the same functionality as mem dashboard in Rstudio program?
I can only make black and white pictures using "full.series.graph" from the MEM package.
It's not clear to me if this function is correct.

**Comment by 13367356107** [comment]
![series graph](https://user-images.githubusercontent.com/105748375/181916505-c8d9fd96-cb80-4aa9-bd62-73576439a93e.png)
![微信截图_20220730212917](https://user-images.githubusercontent.com/105748375/181916536-adfca905-1bab-49bf-80ac-a4c4f16ac6ec.png)

**Comment by lozanoje** [comment]
mem package has its own function full.series.graph to draw the data as a time-series plot, in memapp was totally rewritten to be more informative, but all those graphs are pre generated and you can’t modify them, they are just static images.
I fear that if you want to make custom graphs you have to create by yourself, maybe using first the transformdata.back function to have the data in year, week, rate format
![](https://www.rdocumentation.org/packages/mem/versions/2.8/topics/transformdata.back)

**Comment by 13367356107** [comment]
Thank you very much for your guidance
