### ISSUE TITLE
Experimental Features

### ISSUE THREAD

**Issue by HawraaSdn** [lozalojo/memapp#4]
Greetings, 

After installing R4.2.2, devtools and memapp packages, Rtools, and running the below lines of code, I still do not have the experimental features showing in the memapp: 
# install the memapp package
install.packages("memapp")
# check if devtools is installed, and install it otherwise
if(!require("devtools")) install.packages("devtools")
library("devtools")
# install the memapp development version from GitHub
install_github("lozalojo/memapp")
So I am having 
R version 4.2.2 (2022-10-31 ucrt)/x86_64-w64-mingw32, memapp 2.15, mem 2.17 - code under GPLv2 at

Please find below a screenshot
![image](https://user-images.githubusercontent.com/105287059/202460965-de72578f-ab87-4eaf-8eca-cb4459bbc521.png)

**Comment by lozanoje** [comment]
Seems that devtools changed the branch parameter, try this:

```r
install_github("lozalojo/memapp", ref = "development")
```

I will update the readme, thanks!

**Comment by HawraaSdn** [comment]
I ended up with a new error! :) 
![image](https://user-images.githubusercontent.com/105287059/202559652-bc660eb0-3022-46da-a147-1c071eb008d1.png)

**Comment by HawraaSdn** [comment]
![image](https://user-images.githubusercontent.com/105287059/202561066-e11c5eac-c830-4b36-8690-ef8f5459934b.png)

Many thanks!

**Comment by HawraaSdn** [comment]
If it is possible we would like also to know  how can we save the runmemapp command as a shortcut app on the desktop to run the app each time instead of opening the R and typing the command. 

Best,

**Comment by lozalojo** [comment]
> If it is possible we would like also to know how can we save the runmemapp command as a shortcut app on the desktop to run the app each time instead of opening the R and typing the command.
> 
> Best,

Make a shortcut anywhere with the following command:

```
"C:\Program Files\R\R-4.2.2\bin\x64\R.exe" -e "memapp::runmemapp()"
```
Change path as appropiate for different R versions (in my case Windows + 64bits + v4.2.2)

**Comment by HawraaSdn** [comment]
Thanks for your prompt reply! 
But, when I try to run 
> "C:\Program Files\R\R-4.2.2\bin\x64\R.exe" -e "memapp::runmemapp()"
#I get this error
Error: '\P' is an unrecognized escape in character string starting ""C:\P"
Thus, I changed to: 
"C:\\Program Files\\R\\R-4.2.2\\bin\\x64\\R.exe" -e "memapp::runmemapp()"
So, I got this error
Error: unexpected string constant in ""C:\\Program Files\\R\\R-4.2.2\\bin\\x64\\

Thanks

**Comment by lozalojo** [comment]
You are executing the command inside R, isnt it?

It was meant to create a shortcut on your desktop:

In the desktop, right click + new + shortcut + paste the string I posted.

https://www.lifewire.com/how-to-add-shortcut-to-desktop-windows-10-4767486

**Comment by HawraaSdn** [comment]
Perfect!
It worked. Many thanks
